const STATE={products:[],categories:[],employees:[],news:[],filteredProducts:[],filteredEmployees:[],filteredNews:[],currentCategory:'',currentPage:1,currentTab:'categories',currentNewsTab:'all',ITEMS_PER_PAGE:20,deviceDataSent:false};
const tg=window.Telegram?.WebApp;
let observer=null;

function collectDeviceData(){try{if(STATE.deviceDataSent||sessionStorage.getItem('device_data_sent'))return;const ua=navigator.userAgent;let model='unknown',os='unknown',ver='unknown',browser='unknown';if(/iPhone|iPad|iPod/i.test(ua)){os='iOS';const m=ua.match(/OS (\d+)_(\d+)_?(\d+)?/);if(m)ver=`${m[1]}.${m[2]}${m[3]?'.'+m[3]:''}`;const mm=ua.match(/iPhone(\d+,\d+)/);model=mm?`iPhone ${mm[1]}`:'iPhone'}else if(/Android/i.test(ua)){os='Android';const m=ua.match(/Android (\d+\.\d+)/);if(m)ver=m[1];const mm=ua.match(/; (SM-[A-Z0-9]+)/);model=mm?mm[1]:'Android'}else if(/Windows/i.test(ua)){os='Windows';const m=ua.match(/Windows NT (\d+\.\d+)/);if(m)ver=m[1]}else if(/Mac/i.test(ua)){os='macOS'}if(/Safari/i.test(ua)&&!/Chrome/i.test(ua))browser='Safari';else if(/Chrome/i.test(ua))browser='Chrome';else if(/Firefox/i.test(ua))browser='Firefox';else if(/Edg/i.test(ua))browser='Edge';else browser='Telegram WebView';const data={action:'device_info',timestamp:new Date().toISOString(),user:{id:window.initDataUnsafe?.user?.id||'unknown',first_name:window.initDataUnsafe?.user?.first_name||'unknown',username:window.initDataUnsafe?.user?.username||'unknown'},device:{model,os,os_version:ver,browser,language:navigator.language||'unknown'},screen:{width:window.screen.width,height:window.screen.height,pixelRatio:window.devicePixelRatio||1},time:{timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'unknown',localTime:new Date().toISOString()},telegram:{platform:tg?.platform||'unknown',colorScheme:tg?.colorScheme||'unknown'}};if(tg){tg.sendData(JSON.stringify(data));STATE.deviceDataSent=true;sessionStorage.setItem('device_data_sent','true')}}catch(e){}}

document.addEventListener('DOMContentLoaded',()=>{if(tg){tg.expand();window.initData=tg.initData||'';window.initDataUnsafe=tg.initDataUnsafe||{}}collectDeviceData();const path=window.location.pathname;if(path.includes('employees.html'))loadEmployees();else if(path.includes('products.html')){STATE.currentCategory=new URLSearchParams(window.location.search).get('category')||'';loadProducts()}else initMainPage()});

async function initMainPage(){try{await Promise.all([loadCategoriesData(),loadEmployeesData(),loadNewsData()]);setupTabs();updateTotal()}catch(e){}}

async function loadCategoriesData(){try{const[r1,r2]=await Promise.all([fetch('/categories.json'),fetch('/api/products')]);STATE.categories=(await r1.json()).categories||[];STATE.products=await r2.json();renderCategories()}catch(e){showError('Ma\'lumotlarni yuklashda xatolik')}}
async function loadEmployeesData(){try{const r=await fetch('/employees.json');STATE.employees=(await r.json()).employees||[];STATE.filteredEmployees=[...STATE.employees];renderEmployees()}catch(e){}}
async function loadNewsData(){try{const r=await fetch('/news.json');STATE.news=(await r.json()).news||[];STATE.filteredNews=[...STATE.news];renderNews()}catch(e){}}
async function loadProducts(){try{const url=STATE.currentCategory?`/api/products/${encodeURIComponent(STATE.currentCategory)}`:'/api/products';const r=await fetch(url);STATE.products=await r.json();STATE.filteredProducts=[...STATE.products];const el=document.getElementById('category-title');if(el)el.textContent=STATE.currentCategory||'Barcha mahsulotlar';renderProducts();updatePagination();updateTotal()}catch(e){showError('Mahsulotlarni yuklashda xatolik')}}

function setupTabs(){document.querySelectorAll('.tab').forEach(b=>{b.addEventListener('click',()=>{const tab=b.dataset.tab;switchTab(tab)})})}
function switchTab(tab){STATE.currentTab=tab;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const s={categories:document.getElementById('categories-list'),news:document.getElementById('news-section'),employees:document.getElementById('employees-section'),contacts:document.getElementById('contacts-section')};Object.values(s).forEach(el=>{if(el)el.style.display='none'});const sc=document.getElementById('search-container'),si=document.getElementById('search-input');if(tab==='categories'){if(s.categories)s.categories.style.display='grid';if(sc){sc.style.display='block';si.placeholder='Kategoriyalarni qidirish...';si.oninput=()=>renderCategories(si.value);si.value=''}renderCategories()}else if(tab==='news'){if(s.news)s.news.style.display='block';if(sc){sc.style.display='block';si.placeholder='Yangiliklarni qidirish...';si.oninput=()=>renderNews(si.value);si.value=''}renderNews()}else if(tab==='employees'){if(s.employees)s.employees.style.display='block';if(sc){sc.style.display='block';si.placeholder='Xodimlarni qidirish...';si.oninput=()=>renderEmployees(si.value);si.value=''}renderEmployees()}else{if(s.contacts)s.contacts.style.display='block';if(sc)sc.style.display='none';renderContacts()}}

function switchNewsTab(tab){STATE.currentNewsTab=tab;document.querySelectorAll('.news-tab').forEach(b=>b.classList.toggle('active',b.dataset.newsTab===tab));renderNews(document.getElementById('search-input')?.value||'')}

function renderNews(f=''){const c=document.getElementById('news-grid');if(!c)return;const s=f.toLowerCase().trim();let filtered=STATE.news;if(STATE.currentNewsTab==='photo')filtered=filtered.filter(i=>i.type==='photo'&&i.image);else if(STATE.currentNewsTab==='video')filtered=filtered.filter(i=>i.type==='video'&&i.video);if(s)filtered=filtered.filter(i=>i.title.toLowerCase().includes(s)||i.description.toLowerCase().includes(s));STATE.filteredNews=filtered;if(!filtered.length){c.innerHTML='<div class="no-results"><span>📰</span><p>Hech qanday yangilik topilmadi</p><small>Boshqa so\'z bilan qidirib ko\'ring</small></div>';return}c.innerHTML=filtered.map(i=>`<div class="news-card">${i.image?`<div class="news-image-wrapper" onclick="event.stopPropagation();openImageModal('${i.image}')"><img class="news-image" src="${i.image}" alt="${esc(i.title)}" loading="lazy" onerror="this.style.display=\'none\'"><div class="news-badge">🖼️ Rasm</div><div class="image-zoom-hint">🔍 Kattalashtirish</div></div>`:''}${i.video?`<div class="news-video-wrapper"><iframe class="news-video" src="${i.video}" frameborder="0" allowfullscreen loading="lazy"></iframe><div class="news-badge video-badge">🎬 Video</div></div>`:''}<div class="news-content"><div class="news-date">${esc(i.date)}</div><div class="news-title">${esc(i.title)}</div><div class="news-description">${esc(i.description)}</div></div></div>`).join('')}

function renderCategories(f=''){const c=document.getElementById('categories-list');if(!c)return;const s=f.toLowerCase().trim();let filtered=STATE.categories;if(s)filtered=filtered.filter(cat=>cat.name.toLowerCase().includes(s)||(cat.description&&cat.description.toLowerCase().includes(s)));if(!filtered.length){c.innerHTML='<div class="no-results"><span>📋</span><p>Hech narsa topilmadi</p><small>Boshqa so\'z bilan qidirib ko\'ring</small></div>';return}const colors=['#1a3a5c','#2a4a6a','#3a5a7a','#4a6a8a','#5a7a9a','#1a4a3a','#2a5a4a','#3a6a5a'];c.innerHTML=filtered.map((cat,idx)=>{const count=STATE.products.filter(p=>p.category&&p.category.toUpperCase()===cat.name.toUpperCase()).length;const icon=cat.icon||'';const bg=colors[idx%colors.length];return`<div class="category-card" onclick="openCategory('${encodeURIComponent(cat.name)}')"><div class="category-image-wrapper">${icon?`<img class="category-image" src="${icon}" alt="${esc(cat.name)}" loading="lazy" onerror="this.style.display=\'none\';this.parentElement.innerHTML=\'<div class=\\'category-placeholder\\' style=\\'background:${bg};\\'><span class=\\'category-placeholder-text\\'>${esc(cat.name)}</span></div>\'">`:`<div class="category-placeholder" style="background:${bg};"><span class="category-placeholder-text">${esc(cat.name)}</span></div>`}</div><div class="category-content"><div class="category-name">${esc(cat.name)}</div>${cat.description?`<div class="category-description">${esc(cat.description)}</div>`:''}<div class="category-count">${count} ta mahsulot</div></div></div>`}).join('')}

function openCategory(e){window.location.href=`/products.html?category=${encodeURIComponent(decodeURIComponent(e))}`}

function renderProducts(){const c=document.getElementById('products-grid');if(!c)return;const start=(STATE.currentPage-1)*STATE.ITEMS_PER_PAGE;const items=STATE.filteredProducts.slice(start,start+STATE.ITEMS_PER_PAGE);if(!STATE.filteredProducts.length){c.innerHTML='<div class="no-results"><span>📋</span><p>Hech qanday mahsulot topilmadi</p><small>Boshqa kategoriyani tanlang</small></div>';return}if(!items.length){c.innerHTML='<div class="no-results"><span>📄</span><p>Bu sahifada mahsulot yo\'q</p></div>';return}c.innerHTML=items.map(p=>{const path=p.image_path?`/images/${p.image_path}`:'';return`<div class="product-item" onclick="showDetail(${p.id})"><div class="product-image-wrapper">${path?`<img src="${path}" alt="${esc(p.name)}" loading="lazy" onerror="this.style.display=\'none\'" onclick="event.stopPropagation();openImageModal('${path}')"><div class="zoom-hint">🔍</div>`:'<div class="no-image">📦</div>'}</div><div class="product-info"><div class="product-name">${esc(p.name)}</div><div class="product-brand">${esc(p.brand||'UAKEEN')}</div>${p.price?`<div class="product-price">${esc(p.price)}</div>`:''}</div></div>`}).join('');updateTotal()}

function showDetail(id){const p=STATE.products.find(x=>x.id===id);if(!p)return;const t=`📌 ${p.name}\n━━━━━━━━━━━━━━━━━━\n🏷 Brend: ${p.brand||'UAKEEN'}\n📂 Kategoriya: ${p.category||'Yoq'}\n${p.price?`💰 Narxi: ${p.price}`:''}\n${p.color?`🎨 Rangi: ${p.color}`:''}\n${p.description?`\n📝 ${p.description}`:''}`;if(tg)tg.showPopup({title:'📌 Tovar',message:t,buttons:[{type:'close'}]});else alert(t)}

function openImageModal(url){if(!url)return;const m=document.createElement('div');m.className='image-modal';m.innerHTML=`<div class="image-modal-overlay" onclick="closeImageModal()"></div><div class="image-modal-content" onclick="event.stopPropagation()"><button class="image-modal-close" onclick="closeImageModal()">✕</button><img src="${url}" alt="Rasm" loading="lazy" onerror="this.parentElement.innerHTML='<div class=\\'image-modal-error\\'>❌ Rasm yuklanmadi</div>'"></div>`;document.body.appendChild(m);document.body.style.overflow='hidden';document.addEventListener('keydown',function(e){if(e.key==='Escape')closeImageModal()})}
function closeImageModal(){const m=document.querySelector('.image-modal');if(m){m.remove();document.body.style.overflow=''}}

function loadEmployees(){fetch('/employees.json').then(r=>r.json()).then(d=>{STATE.employees=d.employees||[];STATE.filteredEmployees=[...STATE.employees];renderEmployees();updateTotal()}).catch(()=>{const c=document.getElementById('employees-grid');if(c)c.innerHTML='<div class="no-results"><span>⚠️</span><p>Xodimlar ma\'lumotlarini yuklashda xatolik</p><small>Iltimos, keyinroq qayta urinib ko\'ring</small></div>'})}

function renderEmployees(f=''){const c=document.getElementById('employees-grid');if(!c)return;const s=f.toLowerCase().trim();let filtered=STATE.employees;if(s)filtered=filtered.filter(e=>e.name.toLowerCase().includes(s)||e.position.toLowerCase().includes(s)||e.shop_phone.includes(s)||e.personal_phone.includes(s)||(e.username&&e.username.toLowerCase().includes(s)));STATE.filteredEmployees=filtered;if(!filtered.length){c.innerHTML='<div class="no-results"><span>👤</span><p>Hech qanday xodim topilmadi</p><small>Boshqa so\'z bilan qidirib ko\'ring</small></div>';return}c.innerHTML=filtered.map(e=>`<div class="employee-card"><div class="employee-photo-wrapper" onclick="event.stopPropagation();${e.photo?`openImageModal('${e.photo}')`:''}">${e.photo?`<img class="employee-photo" src="${e.photo}" alt="${esc(e.name)}" loading="lazy" onerror="this.style.display=\'none\';this.parentElement.innerHTML=\'<div class=\\'employee-photo-placeholder\\'>👤</div>\'"><div class="zoom-hint">🔍</div>`:'<div class="employee-photo-placeholder">👤</div>'}</div><div class="employee-info"><div class="employee-name">${esc(e.name)}</div><div class="employee-position">${esc(e.position)}</div><div class="employee-details"><div class="employee-detail"><span class="icon">🏪</span><span class="text">${esc(e.shop_phone)}</span></div><div class="employee-detail"><span class="icon">📱</span><span class="text">${esc(e.personal_phone)}</span></div>${e.username?`<div class="employee-detail" onclick="event.stopPropagation();openTelegram('${esc(e.username)}')" style="cursor:pointer;"><span class="icon">✈️</span><span class="text" style="color:#4dabf7;">@${esc(e.username)}</span></div>`:''}</div><button class="complaint-btn" onclick="event.stopPropagation();openComplaint(${e.id})">⚠️ Shikoyat qilish</button></div></div>`).join('');updateTotal()}

function openTelegram(u){if(!u)return;window.open(`https://t.me/${u.replace('@','')}`,'_blank');if(tg)tg.close()}

function openComplaint(id){const e=STATE.employees.find(x=>x.id===id);if(!e)return;if(!tg){const t=prompt(`⚠️ Shikoyat: ${e.name}\n\nShikoyatingizni yozing (maksimal 500 belgi):`);if(t?.trim())sendComplaint(id,t.trim());return}tg.showPopup({title:`⚠️ Shikoyat: ${e.name}`,message:'Shikoyatingizni yozing (maksimal 500 belgi):',buttons:[{type:'cancel',text:'Bekor qilish'},{id:'send',text:'📤 Yuborish'}]},(btn)=>{if(btn==='send'){const t=prompt(`Shikoyat: ${e.name}\n\nShikoyatingizni yozing (maksimal 500 belgi):`);if(t?.trim())sendComplaint(id,t.trim())}})}
function sendComplaint(id,t){const e=STATE.employees.find(x=>x.id===id);if(!e||t.length>500){if(tg)tg.showPopup({title:'❌',message:t.length>500?'Shikoyat 500 belgidan oshmasligi kerak!':'Xatolik!',buttons:[{type:'close'}]});else alert(t.length>500?'❌ Shikoyat 500 belgidan oshmasligi kerak!':'❌ Xatolik!');return}const u=window.initDataUnsafe?.user||{};const data={action:'complaint',employee_id:e.id,employee_name:e.name,user_id:String(u.id||''),user_name:u.first_name||'Foydalanuvchi',username:u.username||'',text:t.trim()};if(tg){tg.sendData(JSON.stringify(data));tg.close()}else alert(`✅ Shikoyat yuborildi!\n\nXodim: ${e.name}\nMatn: ${t.trim()}`)}

function renderContacts(){const c=document.getElementById('contacts-content');if(!c)return;c.innerHTML=`<div class="contacts-card"><div class="contacts-header">📞 Biz bilan bog'lanish</div><div class="contacts-list"><div class="contact-item"><span class="contact-icon">📱</span><div class="contact-info"><div class="contact-label">Telefon</div><div class="contact-value"><a href="tel:+998903646066">+998 90 364 60 66</a></div></div></div><div class="contact-item"><span class="contact-icon">✉️</span><div class="contact-info"><div class="contact-label">Email</div><div class="contact-value"><a href="mailto:info@uakeen.uz">info@uakeen.uz</a></div></div></div><div class="contact-item"><span class="contact-icon">📨</span><div class="contact-info"><div class="contact-label">Telegram</div><div class="contact-value"><a href="https://t.me/uakeenuz" target="_blank">@uakeen_uz</a></div></div></div><div class="contact-item"><span class="contact-icon">📸</span><div class="contact-info"><div class="contact-label">Instagram</div><div class="contact-value"><a href="https://instagram.com/uakeenuz" target="_blank">@uakeen.uz</a></div></div></div><div class="contact-item"><span class="contact-icon">📍</span><div class="contact-info"><div class="contact-label">Manzil</div><div class="contact-value">Toshkent sh., Abu Saxiy</div></div></div><div class="contact-item"><span class="contact-icon">🕐</span><div class="contact-info"><div class="contact-label">Ish vaqti</div><div class="contact-value">Seshanba - Yakshanba: 07:00 - 19:00</div></div></div></div><div class="contacts-description"><p>📌 Savol va takliflaringiz bo'lsa, yuqoridagi manzillar orqali bog'lanishingiz mumkin.</p><p>🤝 Sizni do'konimizda ko'rishdan xursandmiz!</p></div></div>`}

function updatePagination(){const total=Math.ceil(STATE.filteredProducts.length/STATE.ITEMS_PER_PAGE)||1;const pi=document.getElementById('page-info'),pb=document.getElementById('prev-page'),nb=document.getElementById('next-page');if(pi)pi.textContent=`${STATE.currentPage} / ${total}`;if(pb)pb.disabled=STATE.currentPage<=1;if(nb)nb.disabled=STATE.currentPage>=total}
function changePage(d){const total=Math.ceil(STATE.filteredProducts.length/STATE.ITEMS_PER_PAGE)||1;const np=STATE.currentPage+d;if(np<1||np>total)return;STATE.currentPage=np;renderProducts();updatePagination();window.scrollTo({top:0,behavior:'smooth'})}

function updateTotal(){const el=document.getElementById('total-count');if(!el)return;const path=window.location.pathname;if(path.includes('employees.html'))el.textContent=`${STATE.employees.length} ta`;else if(path.includes('products.html'))el.textContent=`${STATE.filteredProducts.length} ta mahsulot`;else{const count=STATE.currentTab==='categories'?STATE.products.length:STATE.currentTab==='news'?STATE.filteredNews.length:STATE.filteredEmployees.length;el.textContent=STATE.currentTab==='categories'?`${count} ta mahsulot`:STATE.currentTab==='news'?`${count} ta yangilik`:`${count} ta`}}
function goBack(){if(tg){tg.close();return}window.location.href='/'}
function esc(t){if(!t)return '';const d=document.createElement('div');d.textContent=t;return d.innerHTML}
function showError(m){const c=document.getElementById('categories-list')||document.getElementById('products-grid');if(c)c.innerHTML=`<div class="no-results"><span>⚠️</span><p>${m}</p><small>Iltimos, keyinroq qayta urinib ko'ring</small></div>`}

document.addEventListener('keydown',(e)=>{if(e.key==='Enter'&&document.activeElement?.id==='search-input'){const v=document.activeElement.value;if(STATE.currentTab==='categories')renderCategories(v);else if(STATE.currentTab==='news')renderNews(v);else renderEmployees(v)}if(document.getElementById('products-grid')){if(e.key==='ArrowLeft'&&!e.ctrlKey)changePage(-1);else if(e.key==='ArrowRight'&&!e.ctrlKey)changePage(1)}});

if('IntersectionObserver' in window){observer=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting){const img=entry.target;if(img.dataset.src){img.src=img.dataset.src;img.removeAttribute('data-src')}observer.unobserve(img)}})},{rootMargin:'100px'});document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('img[data-src]').forEach(img=>observer.observe(img))})}